# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:
  - id: certonid-build
    dir: cli
    binary: certonid
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    goarm:
      - "7"
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/certonid/certonid/cli/version.Version={{.Version}}
      - -X github.com/certonid/certonid/cli/version.GitCommit={{.Commit}}
      - -X github.com/certonid/certonid/cli/version.BuildTime={{.Date}}
  - id: serverless-build
    dir: serverless
    binary: serverless
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/certonid/certonid/cli/version.Version={{.Version}}
      - -X github.com/certonid/certonid/cli/version.GitCommit={{.Commit}}
      - -X github.com/certonid/certonid/cli/version.BuildTime={{.Date}}

archives:
  - id: certonid-archive
    builds:
      - certonid-build
    name_template: >-
      certonid_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
  - id: serverless-archive
    builds:
      - serverless-build
    name_template: >-
      serverless_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}"

signs:
  - artifacts: checksum
    args: ["--batch", "-u", "{{ .Env.GPG_FINGERPRINT }}", "--output", "${signature}", "--detach-sign", "${artifact}"]

sboms:
  - artifacts: archive

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  -
    name: certonid
    ids:
    - certonid-archive
    goarm: "7"
    # GitHub/GitLab repository to push the formula to
    repository:
      owner: certonid
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"

    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    directory: Formula
    homepage: "https://github.com/certonid/certonid"
    description: "Serverless SSH Certificate Authority"
    license: "MIT"
    test: |
      system "#{bin}/certonid", "--version"
    install: |
      bin.install "certonid"
