language: go

before_install:
- go get github.com/mitchellh/gox

os: linux
dist: bionic

notifications:
  email: false

env:
  global:
    - CERTONID_VERSION=$TRAVIS_TAG

jobs:
  include:
  - go: '1.15.x'
    env: LATEST=true
  - go: '1.14.x'
  - go: '1.13.x'
  - go: tip
  allow_failures:
  - go: tip

before_deploy:
- if [ "${LATEST}" = "true" ]; then ./scripts/build/binary.sh; fi

deploy:
  provider: releases
  edge: true
  overwrite: true
  token:
    secure: QhNFi3S8HnsMOMmgv6SKvXY63pJXKR/5lcU/Kmdvx846i2Mq4HW6zQI8llQd+J7/LeGFrpGyyaQzuWavbiluQFOxIZ6ng7ZoCymbO/GcDD+oiFbl09tPNpHF75kdQlhN/NLVUe44UtuXFKMwb1oVWVUJtBFzJVHABAQk5r7ny9eTJyTmSY85WM2TQ/pxOOpAvfAXRJi3rVOnXJku6c4VT59mONcfb/zk3DiL+X2ZQTYPAKV0DnJVb9XkCcOe4Ix9/rms6Rfgp9ONgWdNyPTRl+fa055vhx7oNJFukn7k4SIbfZjGoNht+YAapWUBKpX6OkaUqPmiULb8fC3f4TOQV1/piXL8c6wfTwP1PLkq3HVV20Rv9XZgTHqBHI167aor9OvJcXCDJxid/objNAkt59nLOHOnfNAlCCDFaliyMV6KW6Ihsct6Y4MwJM7ASQpfd52LIn5l2++hb6SSvswDdOuS40VDsXHja0/4QeCM0yaujZwJW5yo8PrFhhso94p54ArrnZAS/QLwCDd2ZjPkG1yhUuXdeUDm9ae/g2bEOO/SXNju3RXNpo4OuhKUtI16B58bvyULTlap6Tca6PHcYvPNHnKgL/zC8G5dBnzo4nu2BBMfryyhCmtOKiX0ATXbGJRQPaoJ1dfx5mM/P/ivsR2DXsGx6xo8Gl70SRPye8w=
  cleanup: false
  file:
  - certonid.darwin.amd64
  - certonid.linux.amd64
  - certonid.windows.amd64.exe
  - serverless.linux.amd64
  on:
    repo: certonid/certonid
    tags: true
    condition: $LATEST = true
