language: go

before_install:
- go get github.com/mitchellh/gox

sudo: false
dist: xenial

notifications:
  email: false

env:
  global:
    - CERTONID_VERSION=$TRAVIS_TAG

matrix:
  include:
  - go: '1.12'
    env: LATEST=true
  - go: '1.11'
  - go: tip
  allow_failures:
  - go: tip

before_deploy:
- if [ "${LATEST}" = "true" ]; then ./scripts/build/binary; fi

deploy:
  provider: releases
  api_key:
    secure: RNFgr+1/4WVZ+Kk9nR3QaEfvQLl8+r0ZUhdsWpQVggLTnHd/R4UbnRgj9GYwqDkMKc1SHecCg12A4L+E5+i7s9zTVa8o+md+xK1ruZEFuYiBLJprzY+Jaywu+9gJM93XpuZMs8ofIR80Ps7q4kWuONHP5MQsXt95BOtFhxRxYleels+/cBrKuZ8sBvmkl5fqkbFiK6jCWd1G6CJuYKrf7m1ak9XCkZmIGvX42vWuxlM+Ew9MySlqvlq3p+2aJCtQV6YLAKqxJn/8NhCCaDk776Ae+KXqdnrTdZzFARcOxDXo+M+uXYkm04h2B/9vo8ATLugyxANI5Mf/llD9jRlbLlAriSfsF7S7LilhckYWFumlHblzIr2Q7WqLujqU19+63HmiQof2MGG8tdfnJC15h3EcT4y+zTFRp7SnAkAwT5c2Bjbe/K+eTewZ9DaA2ZzgATDc0qw5IHUGwOIzAtWqz4Ofc2apFwaz2tT68eXZ8NoxfQijP9bxqyu2RX68iHigMQktvLUehyEycD+7v9AeZtHgxkVmvANL87qvv7PCFnJYZhfLlbQ1PERgGjqizzktoFRO089OMtY7ysTNw0CkW7OFjsGj8BYUF2SRvlhHS+sKwzNY7SzrHB8kp+xF3NWwStInGknmGTpKbuy1DOBe7148QgLfnYyCn4095rUTJNo=
  skip_cleanup: true
  file:
  - certonid.darwin.amd64
  - certonid.linux.amd64
  - certonid.windows.amd64.exe
  - serverless.linux.amd64
  on:
    repo: le0pard/certonid
    tags: true
    condition: $LATEST = true
