cache_path: ~/.projects_certs
certificates:
  example:
    public_key_path: ~/.ssh/id_ed25519.pub
    username: leopard
    runner: aws
    aws:
      profile: example
      region: us-east-1
      function_name: BressFunction
      kmsauth:
        key_id: ''
        service_id: ''
