cache_path: ~/.projects_certs
certificates:
  example:
    public_key_path: ~/.ssh/id_ed25519.pub
    username: leopard
    runner: aws
    timeout: 10
    aws:
      profile: example
      region: us-east-1
      function_name: BressFunction
      kmsauth:
        key_id: arn:aws:kms:key-id
        service_id: some-service
        valid_until: 24h
    failover:
    - region: eu-central-1
    - region: eu-west-1
      function_name: BackupBressFunction
