ca:
  storage: file
  path: ca.pem
  passphrase:
    encryption: symmetric
    content: 'AQICAHhBwiHijA5XW9EyanTVga4XbbwEVCmBLSUiWIxrCrxrUwHeOnd4YE9LeJlQHr2CwZ0LAAAAZDBiBgkqhkiG9w0BBwagVTBTAgEAME4GCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMsRaxY7GegkhvGxIYAgEQgCH/pghC/EgexphP9CwTBsOGKZXY4UqN0AN7YP9HdNNqHK8='

certificates:
  user:
    max_valid_until: 86400
    additional_principals:
      - "ubuntu"
      - "ec2-user"
    critical_options:
      - "source-address 0.0.0.0/0"
    extensions:
    - "permit-X11-forwarding"
    - "permit-agent-forwarding"
    - "permit-port-forwarding"
    - "permit-pty"
    - "permit-user-rc"
  host:
    max_valid_until: 86400
    additional_principals:
      - "example.com"
    critical_options:
      - "source-address 0.0.0.0/0"
    extensions:
      - "permit-X11-forwarding"
      - "permit-agent-forwarding"
      - "permit-port-forwarding"
      - "permit-pty"
      - "permit-user-rc"

logging:
  level: info
