name: "Build and Release"

on: push

permissions:
  contents: write
  id-token: write
  packages: write

env:
  GO_VERSION: 1.21.4

jobs:
  build-and-release:
    name: "Build and Release"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: CLI tests
        run: |
          go mod tidy
          go test -v ./...
        working-directory: cli

      - name: Serverless tests
        run: |
          go mod tidy
          go test -v ./...
        working-directory: serverless

      - name: Setup Syft for SBOM
        uses: anchore/sbom-action/download-syft@v0
        if: success() && startsWith(github.ref, 'refs/tags/')

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v6
        if: success() && startsWith(github.ref, 'refs/tags/')
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        if: success() && startsWith(github.ref, 'refs/tags/')
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
